### PR TITLE
Unison with fsevents

### PR DESCRIPTION
**Pull request by mickaelperrin**
This PR adds support (optionnal) for `fsevents` on the container side.

Fsevents is compiled from source (note that build-base is not deleted, because fsevents needs some library event after compilation).

Fsevents and unison are managed with supervisor.

Entrypoint has been rewritten and supports additionnal start-up scripts and easy "ssh" into the container with `docker exec -it container_name bash`.

Configuration is done mainly through additional env variables.

### CODE REVIEW

**Comment by onnimonni** [comment]
Did you do any comparison? I thought that by having `unison-fsmonitor` solves the need for fsevents?

**Comment by onnimonni** [comment]
But why would you need to connect back to the host in the first place? Since unison takes care of the 2-way sync?

**Comment by EugenMayer** [comment]
are you sure this works? since even in docker-sync we trigger unison with fswatch. Or lets say it this way, does the OSX version of unison really implement change-watching - AFAIK it does not

**Comment by onnimonni** [comment]
It doesn't by default but we can use: https://github.com/hnsl/unox instead for osx.

I documented this all in https://github.com/onnimonni/docker-unison readme.

**Comment by mickaelperrin** [comment]
There is no native implementation of `unison-fsmonitor` for OSX, that's why we need fswatch.

But, I can confirm with a basic test I got files synced without fswatch. Will now test how it works with a `composer` test.

**Comment by onnimonni** [comment]
I would still prefer unox over fswatch. Then unison can take care of everything even though this isn't native implementation.

**Comment by EugenMayer** [comment]
we can implement different watch strategies without issues

**Comment by mickaelperrin** [comment]
Didn't get the point that this PR has a silly side effect, that it currently sizes 400MB !! I will try to reduce that and opened [an issue](https://github.com/emcrisostomo/fswatch/issues/127) to get `fswatch` as a package.

Regarding the use of `fswatch` instead of `unison`, I am afraid that `unison` simply perform a regular sync for each event (needs to be confirmed). This can cause a very high CPU usage when bootstrapping a lot of files. `fswatch` with the file filters, the events filters `-name` and the `-o` drastically reduces the unison calls.

**Comment by EugenMayer** [comment]
@mickaelperrin the current image has a size of 14mb (you maybe branched of earlier) @onnimonni worked on it see https://github.com/EugenMayer/docker-unison/pull/2 - this could also reduce your image size

So what you added adds a **lot more** for the default strategy - it is just not the same anymore for people using unison, not unison_ng. It also can introduce issues - thats how software works :)

I would use a branch and see how things work out in the future - if unison_ng really is solid ( in more envs then your, mine and 1 other ) it will simply replace unison, and the default master here and the default image. 

Lets call it the save way, right now as a sidepath - if it is battle proven ( i will test this myself in my company ) i am very eager to see this replacing unison and unison even replacing rsync as the default.

**Comment by EugenMayer** [comment]
if you like, join me on #docker-sync in freenode - we can have a talk there briefly.

**Comment by mickaelperrin** [comment]
The size issue is related to the fact that `fswatch` needs some libraries installed by the `build-base`. 

Here is the error I get when I removed it:

    Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/bin/fswatch)
    Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/fswatch)
    Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/libfswatch.so.6)
    Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/lib/libfswatch.so.6)

I will join on #docker-sync later in the night, I will see if you will be there.

**Comment by EugenMayer** [comment]
so it is dynamically linked, well we cannot change that most probably. See you later

**Comment by mickaelperrin** [comment]
I slim it down to around 70MB, the problem is in fact `supervisor` that requires `python` (60MB)

**Comment by EugenMayer** [comment]
Nice work @mickaelperrin you really bringing this forward!

**Comment by EugenMayer** [comment]
Due to you huge effort here and now quiet some difference between the original image, i changed the readme of this project https://github.com/EugenMayer/docker-unison thank you for the hard work!

**Pull request merged**
