### PR TITLE
Remove ocaml build dependency from the image

### PR DESCRIPTION
**Pull request by onnimonni**
unison binaries don't need those and this way the image can then be smaller.

### CODE REVIEW

**Comment by onnimonni** [comment]
After this the image drops from 196.3MB -> 14.41MB

**Comment by EugenMayer** [comment]
Hm, conflicting - any idea? @onnimonni 
Great contribution, plain awesome. thats a huge downsizing aspect!

**Comment by onnimonni** [comment]
It seems that when I updated the readme (2min ago) it created a conflict.

**Comment by EugenMayer** [comment]
You have based on the older readme, check the current master, the readme is very downstripped.

Not sure we need your readme additions here though, i would rather leave the readme as is, to redirect all people wanting to derive/build on do something to your project, since thats were it should happen

**Comment by onnimonni** [comment]
Just wait for one moment and i will create a new pull request without the readme changes.

**Comment by onnimonni** [comment]
PR https://github.com/EugenMayer/docker-unison/pull/2 will have the same fix without changes to readme.

**Pull request closed without merging**
